== Innovate Everywhere Recipes

The latest version of the recipe book can be found here:
https://suse.github.io/recipebook/recipes.html

* Clone the repo and open rezepte.adoc locally in a browser that supports
  AsciiDoc or in another tool such as asciidoctor

* Open this project in
  https://gitpod.io/#https://github.com/SUSE/recipebook[gitpod] and edit it
  directly there.

* The GitHub preview of the in-development recipes is at
<<rezepte.adoc#>>.

=== Contributing

Want to help? We love to hear that! Below are a few hints to guide you.

1. Create a new recipe file under rezepte/<appropriate_directory>/
   Consider copying the recipe_template.adoc from the top level folder
   to have a baseline to work from.
2. Make sure you include a section identifier `[id='sec.recipe_name']` and a title `=== Recipe Name`
   each on their own line and separated by an empty line from other content
3. Add a reference to the new recipe to rezepte.adoc in the top level
4. Add any images to images/<recipe_name>/
5. build the docs with docbuild.sh (requires asciidoctor, see below for install details)
6. check the output at build/rezepte.html to verify it matches the formatting you want

It is recommended to start your recipe by copying recipe_template.adoc from the top
level folder. Alternately, look at the existing recipes to copy the formatting for
setting the images folder, which is a little awkward as we want it to render correctly
with github's preview.

==== Writing

These release notes are written in the AsciiDoc (`*.adoc`) format. For some
great AsciiDoc documentation, see https://asciidoctor.org/docs/asciidoc-writers-guide/.

Viewing asciidoc is most easily done via a plugin to Chrome such as
https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia

Add your recipe under rezepte/<recipe-type> ... desserts go under rezepte/desserts for example

Images associated with the recipe should be added under the images folder at the top level, then
inside a sub-folder with the recipe name

Asciidoctor can be installed for Leap 15.2 at
https://software.opensuse.org/package/rubygem-asciidoctor Other
distributions can be found at
https://asciidoctor.org/#a-linux-package-managers. You can also
install it using bundler or via gem directly:
[source,shell]
----
bundle install
# or
gem install asciidoctor
----

After installing asciidoctor, run the build:
[source,shell]
----
./docbuild.sh
# or if you installed asciidoctor via bundler
bundle exec -- ./docbuild.sh
----
The output of the build will be build/rezepte.html


== Beliebiges Rezept in Mealie-JSON-Format umwandeln

[source, bash]
----
./mealie.py -u <rezept_url>
----


= Workspace Setup

Python
```
pip install rotunicode
```

Asciidoctor
```
gem install asciidoctor
gem install asciidoctor-pdf
```

Executables

```
chmod u+x *.sh *.py
```

== Workflows

=== Neues Rezept aus dem Internet hinzufügen:

```
./mealy.py -u <url>

# Erzeugtes .rmd-File anpassen, unter src/rmd/ hinterlegen

# Erzeuge index.adoc aus .rmd-Files
./rmd_to_asciidoc.py src/rmd/*.rmd

# Erzeuge index.html aus AsciiDoc-Files
./docbuild.sh
```

= GitHub Workspace
Initialisierung
```
sudo apt-get update
sudo apt-get -y install asciidoctor
```


= ChatGPT Rezeptvereinfachung

Ich erkläre dir jetzt eine Markup-Sprache für Rezepte anhand eines Beispiels im folgenden Code-Block.
Zeilen wie ":yields: 4" definieren einen Header mit Rezept-Metadaten. yields steht für die Anzahl von Portionen.

Zutaten werden pro Zeile angegeben, beginnend mit einer Mengenangabe. Unterstrich _ steht für Zutaten ohne Mengenangaben. In Klammern werden Zutaten konkretisiert, so erklärt "Erdnüsse (geröstet, gesalzen)" welche Art von Erdnüssen benötigt werden. Nach einem Semikolon ; werden Zusatzangaben zur Verarbeitung der jeweiligen Zutat beschrieben, die nicht nochmal in den späteren Arbeitsschritten erwähnt werden müssen.

Arbeitsschritte werden direkt nach einer oder mehreren Zutaten mit einem Hashtag (#) beschrieben.

Ich werde Dir in diesem Chat unstrukturiertes Rezept kopieren, oder ggf. URLs zu Rezepten. Bitte konvertiere das in die Markup-Sprache, zeige das Resultat also Code-Block an.
Schlage einen Dateinamen (in Kleinbuchstaben, Snake-Case) für das Rezept mit der Endung ".rmd" vor. Bitte erstelle auch einen Download-Link, um das Rezept als Datei aus dem Chat herunterzalden.



```
Asiatisches Rindfleisch mit Zuckerschoten und Champignons
:yields: 4
:category: Fleischgerichte
:tags: Rind;leicht;Low Carb;Mikrowelle;Büro; Hauptgericht; nur noch garen; Asien
:source: EDEKA

6 EL Sojasoße
3 EL Limettensaft
1 EL Zucker, braun
1 TL Stärke
4 EL Wasser
# verrühren

250g Reis
# kochen

400g Rinderfilet; schnetzeln
1 EL rote Currypaste
# in Gefrierbeutel durchkneten, dann in 2 EL Öl 4 min scharf anbraten, herausnehmen

500g Zuckerschoten
250g Champignons; halbieren
2 Zehen Knoblauch; fein hacken
20g Ingwer; fein hacken
_ Salz
2 EL Rapsöl
# in Öl 8 min bissfest anbraten
Sojamischung und Fleisch zugeben, aufkochen, salzen

80g Erdnüsse (geröstet, gesalzen); grob hacken
# auf Reis und Fleisch servieren
```
