:imagesdir: images
:lang: DE
:hyphens:

:docinfo:

= Rezepte
:pdf-page-size: A5
:toc:

Quelle: https://github.com/SUSE/recipebook.


[%always]
<<<
[id='sec.appetithaeppchen']
== Appetithäppchen

[%always]
<<<
include::rezepte/appetithäppchen/hackfleischtaschen.adoc[]

[%always]
<<<
include::rezepte/appetithäppchen/käsegebäck.adoc[]


[%always]
<<<
[id='sec.beilagen']
== Beilagen

[%always]
<<<
include::rezepte/beilagen/pesto.adoc[]

[%always]
<<<
include::rezepte/beilagen/hummus.adoc[]

[%always]
<<<
include::rezepte/beilagen/semmelknödel.adoc[]

(((Reis, Tomatenreis)))
(((Tomatenreis)))

=== Tomatenreis

[%always]
<<<
[id='sec.salat']
== Salat

[%always]
<<<
include::rezepte/salat/avocado_bulgur_salat.adoc[]


[%always]
<<<
[id='sec.pasta']
== Pasta

[%always]
<<<
include::rezepte/nudeln/fettuccine_alfredo.adoc[]

[%always]
<<<
include::rezepte/nudeln/lemon_tagliatelle.adoc[]

[%always]
<<<
include::rezepte/nudeln/ragu_alla_bolognese.adoc[]

[%always]
<<<
include::rezepte/nudeln/tagliatelle_alla_emiliana.adoc[]


[%always]
<<<
[id='sec.fisch']
== Fisch

[%always]
<<<
include::rezepte/fisch/curry_mango_garnelen.adoc[]

[%always]
<<<
[id='sec.vegetarisches']
== Vegetarisches

[%always]
<<<
include::rezepte/vegetarisches/linsencurry_mit_spinat.adoc[]

(((Spargel und Eier mit French Dressing)))

=== Spargel und Eier mit French Dressing

<<_5Z>>, S. 165

(((Pilztopf)))

=== Pilztopf

(((Paprikaauflauf mit Feta)))
(((Auflauf, Paprikaauflauf mit Feta)))
(((Feta, Paprikaauflauf mit Feta)))

=== Paprikaauflauf mit Feta

(((Pappa al Pomodoro)))

=== Pappa al Pomodoro

<<_5Z>>, S. 173

(((Indischer Eintopf)))
(((Eintopf, Indischer Eintopf)))

=== Indischer Eintopf

(((Ofenkartoffeln)))
(((Kartoffeln, Ofenkartoffeln)))

=== Ofenkartoffeln Kräuterquark / Sour Cream

(((Pfifferlinge auf Brot)))
(((Brot, Pfifferlinge auf Brot)))

=== Pfifferlinge auf Brot

(((Indisches Dal)))
(((Dal, Indisches Dal)))

=== Indisches Dal

(((Shakshuka)))

=== Shakshuka

(((Halloumi-Pilz-Paprika-Spieße)))
(((Spieße, Halloumi-Pilz-Paprika-Spieße)))

=== Halloumi-Pilz-Paprika-Spieße

(((Süßkartoffeln Cajun-Style)))
(((Kartoffeln, Süßkartoffeln Cajun-Style)))

=== Süßkartoffeln Cajun-Style

<<_5Z>>, S. 174

(((Ratatouille-Tarte)))

=== Ratatouille-Tarte

(((Zucchini mit Ziegenkäsefüllung und Thymian)))

=== Zucchini mit Ziegenkäsefüllung und Thymian

(((Auberginen-Pizza vom Grill)))
(((Pizza, Auberginen-Pizza vom Grill)))

=== Auberginen-Pizza vom Grill

(((Kartoffel-Curry)))

=== Kartoffel-Curry

[source]
----
2 1/2 TL gem. Koriander
1 TL gem. Kreuzkümmel
2 TL gem. Kurkuma
eine Prise gem. Nelken
eine Prise frisch gem. Muskatnuss
4 EL Olivenöl
1 Zwiebel, gehackt
4 Knoblauchzehen, fein gehackt
1 1/2 EL Ingwer, fein gehackt
1 rote Chili, fein geschnitten
1 Prise Meersalz
1 Zimtstange
2 Sternanis
400 ml Kokosmilch
300 g Kartoffeln, geschält und in Würfel (2 cm)
geschnitten
800 g Kichererbsen (aus der Dose mit Flüssigkeit)

Garnieren: 4 EL Korianderblätter, gehackt
----

Zubereitung:
In einer kleinen Schüssel den Koriander, den Kreuzkümmel, die Kurkuma, die Nelken und die Muskatnuss mischen und mit 3 EL Wasser vermengen.

Das Olivenöl in einem Topf erhitzen. Dann die Zwiebel, den Knoblauch, den Ingwer, den Chili und das Salz hinzufügen und alles ca. 5 Minuten dünsten.

Wenn die Zutaten anfangen sich gold zu färben, die Gewürzmischung, die Zimtstange und den Sternanis hinzufügen. Alles 1 Minute aufkochen lassen und
dann für ca. 30 Minuten ruhen lassen.

Danach die Kokosmilch, die Kartoffeln und die Kichererbsen (inklusive Flüssigkeit) unterrühren. Das Salz und den Zucker hinzufügen und alles für 15-20 Minuten bei mittlerer Hitze köcheln lassen. Falls die Kartoffeln noch nicht gar sind, die Kochzeit verlängern.


Zum Schluss das Curry noch einmal abschmecken und mit dem Koriander bestreuen.

Tipp: Wer möchte, kann das Curry mit Basmati-Reis oder Couscous servieren


[%always]
<<<
[id='sec.mehlspeisen']
== Mehlspeisen

Mehlspeisen sind süße oder pikante Gerichte aus Mehl, Eiern, Milch und Zucker. Bekannte Beispiele sind Kuchen, Strudel, Palatschinken und Knödel. Sie sind ein wichtiger Bestandteil vieler Küchen und werden oft als Dessert, Snack oder Hauptgericht serviert.

[%always]
<<<
include::rezepte/mehlspeisen/brioche.adoc[]

[%always]
<<<
include::rezepte/mehlspeisen/naan.adoc[]

[%always]
<<<
include::rezepte/mehlspeisen/waffeln.adoc[]

[%always]
<<<
[id='sec.kuchen']
== Kuchen

[%always]
<<<
include::rezepte/kuchen/zwiebelkuchen.adoc[]


[%always]
<<<
[id='sec.gebaeck']
== Gebäck

[%always]
<<<
include::rezepte/gebäck/schoko_cookies_mit_m_und_ms.adoc[]

[%always]
<<<
[id='sec.basis']
== Basis

[%always]
<<<
include::rezepte/basis/brauner_us_zucker.adoc[]



[%always]
<<<
== Kategorien

=== Schnelle Gerichte
* <<sec.pasta, Pasta-Gerichte>>
* Rührei
* Shakshuka
* Weißwürste
* Wiener

=== Leichte Gerichte

* <<sec.curry_mango_garnelen, Curry-Mango-Garnelen>>
* Indischer Eintopf
* <<sec.linsencurry_mit_spinat, Linsencurry mit Spinat>>
* Pappa al Pomodoro
* Paprikaauflauf mit Feta
* Pilztopf
* Rührei
* Shakshuka
* Spargel mit Eiern und French Dressing
* Süßkartoffeln Cajun-Style


[%always]
<<<
[bibliography]
== Literatur

* [[[_5Z]]] Jamie Oliver. 5-Zutaten-Küche
* [[[_15M]]] Jamie Oliver. 15-Minuten-Küche

ifdef::backend-pdf[]
[%always]
<<<
[index]
== Index
endif::[]