Boeuf Bourguignon
:yields: 3
:category: Fleischgerichte
:tags: FR; Hauptgericht; skalierbar

4 Zweige Thymian
2 Zweige Rosmarin
2 Blätter Lorbeer
# Bouquet garni binden

400g Karotten; Spezial-Cut^4^
1 TL Salz
1/3 TL Zucker
# ziehen lassen
100g Speck
# auslassen, Speck entnehme, Fett belassen
800g Rind (Schulter); grob gewürfelt^1^ à 50-100g
_ Butterschmalz
# portionsweise anrösten, wieder entnehmen
250g Schalotten; ganz
3 Knoblauchzehen
20g Butterschmalz
# leicht andünsten
250g Karotten; dicke Scheiben
250g Knollensellerie; 100g-Stücke^2^
2 EL Tomatenmark 
2 EL Mehl^3^
# zugeben
750ml Rotwein, Burgunder
750ml Rinderbrühe
# ablöschen
_ Bouquet garni
# zugeben, 3h köcheln lassen

750g Kartoffeln; grob gewürfelt
100ml Wasser
_ Salz
# in Salzwasser 20-30 Minuten garen, restl. Wasser abgißen.
20g Butter
_ Salz
# durchpressen
250ml Milch
# einrühren, bis schaumig

100g Speck
400g Champignons; mundgerecht
# anbraten

_ Karotten-Cuts; mit gezogenem Wasser
20g Butter
# garen bis Karotten-Wasser verdunstet ist.
---
^1^ à 50-100g!!
^2^ kann später leichter aus der Soße entnommen werden, besser von Karotten unterscheidbar
^3^ 4 EL Mehl? Dann später weniger Speisestärke?
^4^ https://youtu.be/SQ7mG3C22Q4?t=9m47s 09:47


