Dicke-Bohnen-Salat
:yields: 2
:category: Salate
:tags: Hauptgericht; Vorspeise; nur frisch; nur noch aus dem Kühlschrank holen; vegetarisch; ausprobieren; TODO
:source: J.O., _5-Z-K_, S. 28

1/2 Zwiebeln, rot
1 Staudensellerie; nur die zarten inneren Stangen
1/2 Bund Petersilie, glatt; (15 g)
1/2 Glas weiße Bohnen; (à 660 g)
1 Glas Thunfisch in Öl; (220 g)
# Die Zwiebel schälen, in möglichst feine Streifen schneiden und in einer großen Schüssel mit ½ TL Rotweinessig und I kleinen Prise Meersalz durchkneten.
  Den Sellerie putzen, in Scheibchen schneiden und auf die Zwiebelstreifen hau-fen. Die Petersilienstängel klein schneiden und in die Schüssel geben, anschließend die Blätter hineinzupfen.
  Die Bohnen abtropfen lassen, mit | TL Olivenöl in einer vorgeheizten beschichteten Pfanne verteilen und von einer Seite goldbraun und knusprig braten.
  Anschließend wenden und von der anderen Seite anbraten.
  Je I EL natives Olivenöl extra und Rotweinessig in die Salatschüssel träufeln, den Thunfisch grob hineinstückeln und alles behutsam durchheben. Die knusprig gebratenen Bohnen auf Teller verteilen und den Salat daraufhäufen. Eine kräftige Prise schwarzen Pfeffer darübermahlen und reinhauen.