Falafeln mit Cranberry-Gurken-Salat und Knoblauch-Joghurt
:yields: 2
:category: Vegetarisch
:tags: vegetarisch; ausprobieren
:source: essen&trinken

1 Dose Kichererbsen (265 g Abtropfgewicht)
4 Knoblauchzehen
2 EL getrocknete Datteln
1 TL gemahlener Kreuzkümmel
4 EL Mehl
1 TL Backpulver
1 Ei (Größe M)
1 EL Dattelsirup
8 Stiele glatte Petersilie
_ Salz, Pfeffer
# Knoblauch und Datteln fein schneiden, mit den anderen Zutaten in der Küchenmaschine zu einer glatten Masse verarbeiten, würzen, 15 Minuten kalt stellen

1 Salatgurke; längs halbieren, entkernen, in Scheiben schneiden
4 EL Olivenöl
2 EL Weißweinessig
1 TL Zucker
30 g getrocknete Cranberries; halbieren
4 Stiele Dill
# Olivenöl, Essig, Zucker zu einer Vinaigrette mischen, mit Gurke, Cranberries und Kräutern vermengen

200 g griechischer Joghurt
1 EL Zitronensaft
_ Salz, Pfeffer
# restlichen Knoblauch fein reiben, mit Joghurt und Zitronensaft mischen, abschmecken

_ Öl
# Falafelmasse zu Nocken formen, in heißem Öl 4–5 Minuten frittieren

# Mit Gurkensalat und Knoblauch-Joghurt servieren
