Gulasch vom Wildschwein mit Paprikacreme
:yields: 6
:category: Hauptgericht
:tags: Wild; einfach; gut vorzubereiten
:source: essen&trinken 11/2024

# GULASCH

1.25 kg Wildschweinkeule; Würfeln (2 cm)
2 Zwiebeln; in Streifen
2 Knoblauchzehen; in Scheiben
4 EL Rapsöl
2 EL Paprikamark
1 EL Paprikapulver, edelsüß
1 TL Wacholderbeeren; andrücken
1 TL Pimentkörner; andrücken
2 Lorbeerblätter
6 Stiele Thymian
_ Salz
_ Pfeffer
500 ml Wildfond
500 ml Rotwein
6 rote Spitzpaprika (600 g); in grobe Stücke
1 TL Speisestärke

# Fleisch anbraten, Zwiebeln und Knoblauch andünsten, Paprikamark und Paprikapulver zugeben, restliche Zutaten hinzufügen und schmoren.

# CREME UND SCHWARZWURZELN

2 rote Pfefferschoten; fein schneiden
1 Knoblauchzehe; fein schneiden
2 EL Olivenöl
200 g eingelegte Paprika; abtropfen lassen
1 Bio-Zitrone; abreiben und Saft auspressen
250 g Frischkäse
_ Salz
_ Pfeffer
800 g Schwarzwurzeln; in Stücke schneiden
2 EL Butter (20 g)

# Pfefferschoten und Knoblauch andünsten, Paprika und Frischkäse mixen, abschmecken. Schwarzwurzeln kochen und in Butter anbraten.
