Kartoffel-Curry
:yields: 0
:category: Aufläufe
:tags: Hauptgericht;vegetarisch;leicht;TODO;ausprobieren

2.5 TL Koriander, gem.
1 TL Kreuzkümmel, gem.
2 TL Kurkuma, gem.
1 Prise Nelken, gem.
1 Prise Muskat, gemahlen
4 EL Olivenöl
1 Zwiebel, gehackt
4 Knoblauchzehen, fein gehackt
1 1/2 EL Ingwer, fein gehackt
1 rote Chili, fein geschnitten
1 Prise Meersalz
1 Zimtstange
2 Sternanis
400ml Kokosmilch
300g Kartoffeln; geschält und in Würfel (2 cm) geschnitten
800g Kichererbsen (aus der Dose mit Flüssigkeit)
4 EL Korianderblätter; gehackt

# TODO Zutaten einsortieren
# In einer kleinen Schüssel den Koriander, den Kreuzkümmel, die Kurkuma, die Nelken und die Muskatnuss mischen und mit 3 EL Wasser vermengen.
# Das Olivenöl in einem Topf erhitzen. Dann die Zwiebel, den Knoblauch, den Ingwer, den Chili und das Salz hinzufügen und alles ca. 5min dünsten.
# Wenn die Zutaten anfangen sich gold zu färben, die Gewürzmischung, die Zimtstange und den Sternanis hinzufügen. Alles 1 Minute aufkochen lassen und dann für ca. 30min ruhen lassen.
# Danach die Kokosmilch, die Kartoffeln und die Kichererbsen (inklusive Flüssigkeit) unterrühren. Das Salz und den Zucker hinzufügen und alles für 15-20min bei mittlerer Hitze köcheln lassen. Falls die Kartoffeln noch nicht gar sind, die Kochzeit verlängern.
# Zum Schluss das Curry noch einmal abschmecken und mit dem Koriander bestreuen.
# Tipp: Wer möchte, kann das Curry mit Basmati-Reis oder Couscous servieren
