Käse-Lauch-Hackfleisch-Suppe
:yields: 3
:category: Suppen
:source: https://www.einfachmalene.de/kase-lauch-hackfleisch-suppe/

# TODO https://www.einfachmalene.de/kase-lauch-hackfleisch-suppe/

500g Rinderhackfleisch
3 Stangen Lauch
3 EL Olivenöl
1 Zehe Knoblauch
3 TL Rindfleischbrühe
700ml Wasser
200g Schmelzkäse
1/2 Bch Creme Fraiche
1 Pr Muskat
^0 Salz und Pfeffer

# Wasche den Lauch und schneide ihn in schmale Ringe schneiden. Erhitze das Öl im Topf und brate das Hackfleisch darin heiß an bis es krümelig ist.
# Gib den Knoblauch durch eine Presse und dünste dieses kurz mit. Gib nun auch die Lauchringe zum Hackfleisch dazu und dünste diese ca. 5 Minuten mit an. Nun kannst du ca. 700 ml Brühe hinzu geben. Es sollte alles gerade so bedeckt sein. Koche die Suppe anschließend kurz auf.
# Nun kannst du den Schmelzkäse in die warme Suppe geben. Rühre so lange, bis er vollständig geschmolzen ist. Gib nun auch Creme Fraiche hinzu und koche die Suppe noch einmal kurz auf. Schmecke die Hackfleisch Lauch Suppe mit Salz, Pfeffer und Muskat ab.
# Dazu passt frisches Baguette. Besonders lecker ist dieses, wenn es noch einmal kurz in den Backofen geschoben wird. Dann kannst du das knusprige Baguette mit etwas Butter zur Suppe servieren.
