Lammlachse mit Zitronenkruste
:yields: 4
:category: Fleischgerichte
:url: https://www.eatbetter.de/rezepte/lammlachse-mit-kraeuterkruste-aus-dem-backofen

800g Kartoffeln (klein / Drillinge)
# In kochendem Salzwasser 10m vorgaren.

800g grüne Bohnen
# Bohnen putzen und waschen und in kochendem Salzwasser etwa 8 Minuten garen abgießen und kalt abschrecken.
# Den Backofen auf 120 Grad Celsius (Ober-/Unterhitze) vorheizen. Backblech mit Backpapier vorbereiten.

2 Scheibe Toast; fein gewürfelt
1 Knoblauchzehe; gehackt
2 EL Pinienkerne; gehackt
3 Zweig Thymian; gehackt
3 Zweig Rosmarin; gehackt
0.5 Bd. glatte Petersilie; gehackt
1 EL Zitronenabrieb
2 EL Butter; flüssig erhitzt
# Vermengen und durchkneten bis eine feste Masse entsteht. Mit Salz und Pfeffer abschmecken. 

4 Lammlachs (je 125 g)
# In 1 EL Rapsöl ca. 1m scharf anbraten. Auf Backblech legen und die Mischung darauf verteilen. Ca. 15m fertig garen.
# Vorgegarte Kartoffeln halbieren, in 1 EL Rapsöl 10m knusprig braten. Mit Salz und Pfeffer würzen.

2 Schalotten; fein gewürfelt
# Glasig dünsten. Bohnen dazugeben und erhitzen. Mit Salz und Pfeffer abschmecken.
# Lammlachse mit Kartoffeln und Bohnen servieren.
