Marillenknödel
:yields: 3
:category: Mehlspeisen
:tags: ausprobieren; vegetarisch
:url: https://www.gutekueche.at/marillenknoedel-mit-topfenteig-rezept-784

1 Ei
130g glattes Mehl
250g Magertopfen
70g Margarine oder Butter
1 Prise Salz
5 EL Staubzucker zum Bestreuen
6 Marillen
6 Würfelzucker
1 EL Butter
140g Semmelbrösel

# Für den Topfenteig die Margarine (oder Butter) und das Ei flaumig in einer Schüssel verrühren (=abtreiben). Danach den Topfen, Mehl und Salz hinzugeben und gut durchkneten bis ein Teig entsteht.
# Den Teig in 6 gleich große Stücke aufteilen und mit bemehlten Händen die einzelnen Teigteile zu einer flachen runden Teigscheibe drücken.
# Die Marillen gut waschen, abtrocknen und halbieren - dabei den Kern entfernen. Anstelle des Kernes ein Stück Würfelzucker geben und die beiden Marillenhälften wieder zusammensetzen.
# Nun jeweils die beiden Marillenhälften, mit dem Würfelzucker in der Mitte, auf die runden, flachgedrückten Teigstücke geben und mit dem Teig zu einem Knödel formen - die Marillenstücke sollten komplett vom Teig umhüllt sein.
# In einen Topf Salzwasser zum Kochen bringen, die Marillenknödel ins Wasser geben und schwach siedend für ca. 10 - 12 Minuten gar kochen - das merkt man wenn die Knödel an der Wasseroberfläche schwimmen.
# In der Zwischenzeit kann man in einer Pfanne mit einem EL Butter die Semmelbröseln kurz anrösten.
# Zum Schluss die fertig gekochten Topfenknödel in der Pfanne mit den Semmelbröseln wälzen.
# Vor dem Servieren werden die Marillenknödel mit Staubzucker (oder Zimtzucker) bestreut.
