Nusspalatschinken
:category: Mehlspeisen
:tags: ausprobieren;TODO
:yields: 2
:url: https://www.ichkoche.at/nusspalatschinken-rezept-1418

_ Öl
125 ml Milch
60g Mehl
1 Eier
1 Prise Salz
100g Walnüsse
100ml Milch
1 Pkg. Vanillezucker
1 EL Zucker
1 Prise Zimt
1 Prise Kardamom
_ Schlagobers
_ Staubzucker

# Zunächst alle Zutaten für den Teig vermischen und zu einem glatten Teig rühren.
# Für die Nussfülle die Milch langsam gemeinsam mit dem Zucker und dem Vanillezucker aufkochen lassen und danach die Nüsse einrühren. Nach Belieben mit etwas Zimt und etwas Kardamom abschmecken. Die Nussfüllung warm stellen.
# In einer Pfanne wenig Öl erhitzen und gerade so viel Teig eingießen, bis der Pfannenboden bedeckt ist. Die Palatschinke fest werden lassen und wenden. Sobald die Palatschinke auf beiden Seiten goldbraun ist, herausnehmen und warmstellen.
# Weiter so verfahren, bis der Teig aufgebraucht ist und alle Palatschinken fertig sind.
# Nun die Palatschinken mit der Nussfülle bestreichen und einrollen.
# Die Nusspalatschinken am besten mit geschlagenem Schlagobers und mit Staubzucker bestreut servieren.
---
Alkoholische Variante: Nussgeschmack der Nusspalatschinken noch mit einem Schuss Nusslikör oder Nussschnaps in der Füllung intensivieren.
