Pizzakordeln
:category: Gebäck
:tags: ausprobieren; Snacks
:yields: 0
:url: https://www.wochenblatt.com/rezepte/pizzakordeln-fuer-das-picknick-11590472.html

250 g	Mehl
1/2 Päckchen	Trockenhefe
2 Esslöffel	Olivenöl
1 Teelöffel	getrocknete Kräuter der Provence
2 Prisen	Salz
160 ml	Wasser
# Für den Teig alle Zutaten in eine Schüssel geben und mit den Knethaken des Handrührgerätes oder der Küchenmaschine so lange verkneten, bis sich der Teig aus der Topfschüssel löst, eventuell noch einmal vorsichtig etwas Wasser oder Mehl nachgeben.
# Den Teig zugedeckt etwa 30 Minuten in der Schüssel ruhen lassen.
# Ein Backblech mit Backpapier auslegen. Den Back­ofen auf 180 °C Ober- und Unterhitze vorheizen.


4 bis 5 Esslöffel	Tomatenmark
100 g	Reibekäse
0 Salz
0 Olivenöl
# Auf der bemehlten Arbeitsfläche den Teig zu einem Rechteck (ca. 35 x 20 cm) ausrollen. Mit Tomatenmark bestreichen, etwas salzen, mit Käse bestreuen. Nun mit einem Pizzaschneider oder einem scharfen Messer den Teig entlang der kurzen Seite in 2 bis 3 cm breite Streifen schneiden. Die Streifen von unten nach oben einklappen − dabei darauf achten, dass der Käse nicht herausfällt. Die gefalteten Teigstücke zu einer Kordel drehen und auf das Backblech legen. Mit Olivenöl bestreichen.
# Kurz gehen lassen und im heißen Backofen 20 bis 30 Minuten knusprig abbacken.
