Reis mit Pak Choi und Hoisin-Sauce
:yields: 2
:category: Vegetarisches
:tags: Hauptgericht; nur frisch; vegetarisch; ausprobieren; TODO
:source: J.O., _5-Z-K_, S. 260


150 g Basmatireis
4 Frühlingszwiebeln
2 frische Chilischoten in verschiedenen Farben
2 Pak Choi (250 g)
2 EL Hoisinsauce
# Den Reis in Salzwasser nach Packungsangabe kochen, dann in ein Sieb schütten und abtropfen lassen. Inzwischen die Frühlingszwiebeln putzen und in dünne Ringe schneiden. Die weißen Ringe in eine Schüssel geben. Die Chilischoten entkernen und fein hacken, dann mit I EL Rotweinessig sowie etwas Meersalz und schwarzem Pfeffer dazugeben und alles zu einem Dressing verrühren.
  Die Pak Choi längs halbieren, dann mit I EL Olivenöl in eine große beschichtete Pfanne geben und bei mittlerer bis starker Hitze braten, bis sie kräftig gebräunt sind. Die grünen Frühlingszwiebelringe untermischen, dann die Hoisinsauce unterrühren. Alles | Minute kochen lassen, dann den Reis hinzufügen und | Minute unter Rühren erhitzen. Das Chilidressing auf die Pak Choi löffeln und das Gericht servieren.