Warmer Linsensalat mit Sardellen
:yields: 4
:category: Salate
:tags: Hauptgericht; Vorspeise; nur frisch; vegetarisch; ausprobieren; TODO
:source: J.O., _5-Z-K_, S. 36

1 Dose Sardellen in Öl (50 g)
1 Salzzitrone (20 g)
400g Sprossenbrokkoli
1 frische Chilischoten in verschiedenen Farben
500 g gegarte Linsen (Beutel oder Dose)
# Die Sardellen mit ihrem Öl sowie I EL Salzlake von den eingelegten Zitronen und I Schuss Wasser im Mixer glatt pürieren. Falls nötig, noch etwas mehr Wasser dazugeben.
  Den Brokkoli putzen und in einem großen Topf in kochendem Salzwasser 3 Minuten blanchieren, bis er eben weich ist.
  Inzwischen die Zitrone vierteln, das Innere mit den Kernen entfernen, nur die Schale fein hacken. Die Chilis in dünne Ringe schneiden. Den Brokkoli abgießen, zurück in den Topf geben und wieder auf den Herd stellen. Die gehackte Zitrone, den Großteil der Chili-ringe und I EL natives Olivenöl extra untermischen. Die Linsen dazugeben und 2 Minuten erwärmen, dabei behutsam umrühren. Anschließend den Salat auf Teller verteilen, mit dem Sardellendressing übergießen und mit den restlichen Chiiringen bestreuen. Vor dem Servieren mit ½ EL nativem Olivenöl extra abrunden.