Weiße-Bohnen-Salat mit Thunfisch
:yields: 2
:category: Salat
:tags: Hauptgericht; Vorspeise; nur frisch; nur noch aus dem Kühlschrank holen; vegetarisch; ausprobieren; TODO
:source: J.O., _5-Z-K_, S. 22

200g Dicke Bohnen (frisch oder TK)
30g Mandelkerne
1 Glas geröstete rote Paprikaschoten in Lake (480 g)
1/2 Bund glatte Petersilie
30g Manchego
# Die Bohnen in kochendem Salzwasser 3 Minuten blanchieren, dann abgießen.
  Sehr große Bohnenkerne aus der hellen Haut herausdrücken. Die Bohnen in eine Schüssel geben. Die Mandeln in einer Grillpfanne bei mittlerer Hitze goldgelb rösten, dabei regelmäßig durchschwenken. Anschließend in feine Scheibchen schneiden.
  Die einselegten Paprikaschoten abtropfen lassen, falls nötig, aufschneiden, dann in der heißen Grillefanne flach ausbreiten und nur von einer Seite bräunen.
  Herausnehmen und in I cm dicke Streifen schneiden. Die Petersilienstängel klein schneiden, die Blätter abzupfen. Alles zu den Dicken Bohnen geben und mit 1½ EL nativem Olivenöl extra und je I EL Rotweinessig und Paprikalake aus dem Glas vermischen. Den Salat sorgfältig mit Meersalz und schwarzem Pfeffer abschmecken und auf Tellern anrichten.
  Mit einem Sparschäler den Manchero darüberhobeln. Den Saler mir I TL nori-vem Olivenöl extra abrunden, mit den Mandeln bestreuen und servieren.
