[id='sec.semmelknoedel']

ifdef::env-github[]
:imagesdir: ../../images
endif::[]
ifndef::env-github[]
:imagesdir: images
endif::[]

indexterm:[Semmelknödel]
indexterm:[Knödel, Semmelknödel]

=== Semmelknödel
4 Portionen

[width="100%",cols=">20%,30%,50%"]
|===
| 1 |Zwiebel (Würfel) .3+.^|glasieren, mit Milch ablöschen und erwärmen, würzen
|150ml |Milch
|Prise |Muskat
|250g |*Knödelbrot*|mit Zwiebelmasse vermengen, abdecken, 30min ruhen
|||
|1 |Ei (geschlagen) .2+.^|zu Knödelmasse zugeben, vermischen bis die Masse klebrig wird, zu Knödel formen.

_Entweder_ 1min kochen + 15min ziehen lassen _oder_ 20min dämpfen

Dann lufttrocknen, oder bei 70 °C Umluft 10-15min in Ofen antrocknen lassen.
|2 EL|Petersilie
|===

Tipp: Hände feucht halten beim Knödel formen

==== Varianten

Bratknödel: 7-10min pro Seite auf mittlerer Hitze anbraten

Kaspressknödel: Zur Knödelmasse noch 200g Bergkäse verkneten und wie Bratknödel anbraten

Rührei und gebratene Knödelwürfel

Kastenform einfetten, darin Knödelmasse 30-35min in 180°C Umluft backen
